feature/organization donor and recipient tags
sharingexcess/rescue pull request #117
Opened 2021-01-26 17:50 UTC by kennyallex2

- Added donor/recipient tags to both organization pages
- Fixed capitalization for donor and recipient (Some of the current organizations still have old tags which will be updated ASAP because you can't sort them anymore)
- Added a new color
Below are the changes:
![image](https://user-images.githubusercontent.com/71650027/105883251-a2903f80-5fd4-11eb-9c10-e4a4bf6e9db9.png)
![image](https://user-images.githubusercontent.com/71650027/105883320-b9369680-5fd4-11eb-8b49-e85899e275ca.png)

2021-01-26 18:26 UTC, ryanmchenry2 requested changes
Really great work Kenny! Super nit-picky stuff here that I think will align this code better with existing CSS code, but this is a great feature add. Excited to get this merged ASAP 👍

2021-01-26 18:26 UTC, ryanmchenry2 commented on src/components/EditOrganization/EditOrganization.js
> -        suggestions={['donor', 'recipient']}
Let's keep these lowercase for the sake of data consistency - we can always use CSS to capitalize text to put in front of the user, but keeping things all lowercase on the backend will make it much easier to filter and search.

2021-01-26 18:26 UTC, ryanmchenry2 commented on src/components/Organization/Organization.js
> +            <h1>{org.name}</h1>
I'd suggest using an `<h2>` and an `<h3>` tag here - we use the `<h1>` in the <Header /> component, and for accessibility reasons, it's important to use only one `<h1>` per page.

2021-01-26 18:26 UTC, ryanmchenry2 commented on src/components/Organization/Organization.scss
> +          background-color: var(--limegreen);
Is it possible to use one of the existing theme colors for this? Would love to remove the dependency to maintain an additional color `--limegreen` since we have a few greens to choose from. Also, what are your thoughts on color coding this tag for donor/recipient in the same way that we color code pickups and deliveries?

2021-01-26 18:26 UTC, ryanmchenry2 commented on src/components/Organization/Organization.scss
> +          border: 4px solid var(--limegreen);
If we use a colored background, we should be able to remove the border and just use padding, and therefore not need to change the `box-sizing` property

2021-01-26 18:26 UTC, ryanmchenry2 commented on src/components/Organization/Organization.scss
> +          border-radius: 10px 10px;
For borders, margins, and (usually) font-sizes, it's a great best practices to use powers of 2 when possible (2px, 4px, 8px, 16px, etc). A lot of browsers tend to calculate pixels and aspect ratios in similar numbers, so they help avoid off by 1px glitches in CSS. It sounds silly and unnecessary, but it ends up actually being really helpful in picking consistent sizes for elements.

2021-01-26 18:26 UTC, ryanmchenry2 commented on src/components/Organizations/Organizations.js
> -          <option value="donor">
Same feedback from above with lowercase ^^^

2021-01-26 18:26 UTC, ryanmchenry2 commented on src/components/Organizations/Organizations.scss
> +      color: var(--black);
Personal preference, but I think var(--white) would be more readable against the colored background.

2021-01-26 19:51 UTC, kennyallex2 commented on src/components/Organization/Organization.scss
> +          background-color: var(--limegreen);
Yeah, I was thinking of doing something like that earlier. I'll look at the color options and see what two colors would fit well as tags.

2021-01-26 20:09 UTC, ryanmchenry2 commented on src/components/Organization/Organization.scss
> +          background-color: var(--limegreen);
I think just simply --green and --red are what we use in delivery/pickup UI.

2021-01-27 16:33 UTC, ryanmchenry2 approved these changes
This looks awesome. Great improvements for code clarity and consistency here, ship it!

2021-01-27 16:33 UTC, ryanmchenry2 commented on src/components/Organizations/Organizations.scss
> +    h2.donor {
Optional improvement you could make here: instead of adding another identifier of `h2:donor`, you can use SASS nesting to add the selector `&.donor` inside of your `h2` selector, ie:
```
h2 {
  ...
  &.donor {
    background: var(--green);
  }
  &.recipient {
    background: var(--red);
  }
}

2021-01-27 16:37 UTC, tnguyen21 approved these changes
LGTM! The distro team will find this immensely helpful so thanks for working on this!

2021-01-27 16:52 UTC, merged