Add top right begin route button
sharingexcess/rescue pull request #161
Opened 2021-04-05 17:30 UTC by truongductri01

I have finished the ticket, here is my explanation:

1. I add the begin route button (which is identical to the one at the end of the page)
2. I move the willAssign state to the top as a global variable as the button needs that. And also other buttons need to access that same variable, so I think it is reasonable to move it there
3. I put the same handleBegin function in the Driver component.
4. I added a class driver-buttons to the one inside the Driver component for styling purpose
5. Style that button in the scss

![Desktop view](https://user-images.githubusercontent.com/58579187/113604011-4f58ef80-960a-11eb-8e6a-2e1865752442.png)
![Mobile view](https://user-images.githubusercontent.com/58579187/113604084-65ff4680-960a-11eb-8b25-aba4636e0561.png)

**Issues**

1. Repeat handleBegin functions - maybe create a helpers functions file to store those functions
2. The new button will also show up in the top right corner of the admin site

2021-04-05 17:42 UTC, nhatduy227 requested changes
Leave a comment in the code. There is also a bug that I have found. If you are a driver and you are clicking on a routes that is not yours, the 'change recipient' and 'begin route' is still there. We want to hide those.
![Capture](https://user-images.githubusercontent.com/53373898/113605657-f5115c00-9614-11eb-9feb-0d535778ffe6.PNG)

2021-04-05 17:42 UTC, nhatduy227 commented on src/components/Route/Route.js
> +        <div className={`driver-buttons ${admin ? 'buttons' : ''}`}>
"{driver ? && +div+...+/div+}" to show button if user is a driver. Changed '<' to '+' for divs because github will change the format if < stays near div

2021-04-06 13:24 UTC, truongductri01 commented on src/components/Route/Route.js
> +        <div className={`driver-buttons ${admin ? 'buttons' : ''}`}>
I have added in the feature to hide the div from the admin site. 
And is it really a problem to do <div> instead of +div+? I did not see any changes in the format yet

2021-04-06 13:26 UTC, nhatduy227 commented on src/components/Route/Route.js
> +        <div className={`driver-buttons ${admin ? 'buttons' : ''}`}>
Your changes looks good, this message is here before your new commit, no worry

2021-04-06 14:09 UTC, truongductri01 commented
I have added the logic to hide the 'begin route' and 'change recipient' buttons from the driver if they are not in charge of the route.

I would love to meet with Ryan or Nom to understand more about the logic of this feature

2021-04-06 14:11 UTC, nhatduy227 approved these changes
LGTM!

2021-04-06 14:14 UTC, merged