Recurring route logic fix
sharingexcess/rescue pull request #176
Opened 2021-04-20 21:02 UTC by nhatduy227

Fix recurring logic

1. Use a new function name handleCreateRouteButtonClick() to call handleCreateRoute() depends on the number of time require to create a recurrence
2. Every recurrence now has its new ID, which is create using the generateID() using the updated start time. It also has a field name original_route_id to link with the 1st recurrence 
3. Every stop now has its new ID too, which is the original_stop_id + number of iteration. It also has a field name original_stop_id to link with the 1st stop recurrence 

Tested on dev and it works as expected: 
- Recurrences report correct start and end time
- Each recurrence can be complete individually, and delete individually without effecting other route

2021-04-20 21:49 UTC, truongductri01 commented on src/components/EditRoute/EditRoute.js
> +          console.log('Stop Ids >>>', stop.id)
You can remove this log statement

2021-04-20 21:50 UTC, truongductri01 commented on src/components/EditRoute/EditRoute.js
> +          console.log('Stop Ids >>>', stop.id)
This one should be removed also ^^

2021-04-20 22:37 UTC, truongductri01 reviewed
I have tried it and find a bug which I cannot know that cause yet
So basically after the driver finish the route, the pounds still do not show up yet

![image](https://user-images.githubusercontent.com/58579187/115472195-ffc81580-a1fe-11eb-89e2-a668c8a2776b.png)
![image](https://user-images.githubusercontent.com/58579187/115472201-05256000-a1ff-11eb-9e21-072599668dba.png)

Or you can try to reload the page several times, the bug also happened after reloading

2021-04-22 15:12 UTC, ryanmchenry2 requested changes

2021-04-22 15:12 UTC, ryanmchenry2 commented on src/components/EditRoute/EditRoute.js
> +            original_stop_id: stop.original_route_id
Is this correct that you're filling original_stop_id with original_route_id?

2021-04-22 15:12 UTC, ryanmchenry2 commented on src/components/EditRoute/EditRoute.js
> +            original_stop_id: stop.original_route_id
same question here

2021-04-22 15:12 UTC, ryanmchenry2 commented on src/components/EditRoute/EditRoute.js
> +      const event = await updateGoogleCalendarEvent(formData)
Are we creating one recurring google calendar event, or are we using the recurring properties inside google calendar?

I think the better choice would be to make all individual events so that each unique route id has a unique event id. That way the data structure is the same for our system and the calendar events.

2021-04-22 15:44 UTC, nhatduy227 commented on src/components/EditRoute/EditRoute.js
> +            original_stop_id: stop.original_route_id
Oh thanks for pointing it out, it is a mistake on my end

2021-04-22 16:04 UTC, nhatduy227 commented on src/components/EditRoute/EditRoute.js
> +      const event = await updateGoogleCalendarEvent(formData)
Since we call the handleCreateRoute function multiple times, it is safe to say that we create multiple distinct google events on the calendar. We are not using the recurring properties inside google calendar at the moment

2021-04-22 22:33 UTC, ryanmchenry2 approved these changes

2021-04-22 23:01 UTC, merged