Created typeable input boxes in Pickup Report
sharingexcess/rescue pull request #197
Opened 2021-05-13 14:03 UTC by lukeshinnn

1. When creating new route, changed the blue button to say "create route" instead of "complete" for more clarity
2. When completing Pickup Report, user can type numerical input instead of only using +/- buttons
![image](https://user-images.githubusercontent.com/63413560/118136684-6097d780-b3d2-11eb-81a0-943a2e475290.png)

Issue: There are tiny arrows inside of the input box. I think they look sort of ugly and I'm not sure how to get rid of them

2021-05-13 15:57 UTC, nhatduy227 approved these changes
LGTM! This will helps Distro a lot

2021-05-14 13:28 UTC, truongductri01 commented on src/components/PickupReport/PickupReport.js
> +                type="string"
Maybe only allow them to input integer instead of entering random characteristic

2021-05-14 13:30 UTC, truongductri01 requested changes
Maybe look into the method of allowing them to only enter number, instead of strings or special symbols.
Maybe you will have the arrows but there is a way to hide them away

2021-05-14 14:20 UTC, NikRamadhin approved these changes

2021-05-15 16:58 UTC, merged