Bug/home delivery
sharingexcess/rescue pull request #245
Opened 2021-08-16 19:00 UTC by nhatduy227

1. Make address 2 require for home delivery 
2. Hash different unique ID for home delivery locations

2021-08-16 19:29 UTC, ryanmchenry2 requested changes

2021-08-16 19:29 UTC, ryanmchenry2 commented on src/components/EditLocation/EditLocation.js
> +    if (isHomeDelivery && formData.address2 === '') {
I don't think this check is necessary - not every home delivery will have an apartment number.

2021-08-16 19:29 UTC, ryanmchenry2 commented on src/components/EditLocation/EditLocation.js
> +  const isHomeDelivery = organization
I think we can keep this PR simpler than this - the only thing that I think we need to change right now is how we generate the unique ID for the new location.

2021-08-16 19:29 UTC, ryanmchenry2 commented on src/components/EditLocation/EditLocation.js
> +      .toLowerCase()}${address2.replace(/[^A-Z0-9]/gi, '_').toLowerCase()}`
We want to add an additional `_` to separate address1 and address2, but only conditionally if address2 is populated. I think something like this might be the best bet:
```const uniq_id = `${organization.name}_${formData.address1
      }${formData.address2 ? '_' + formData.address2 : ''}`.replace(/[^A-Z0-9]/gi, '_').toLowerCase()```

2021-08-16 19:29 UTC, ryanmchenry2 commented on src/components/EditLocation/EditLocation.js
> -          <div className="is_community_fridge">
Are we no longer supporting community fridges?

2021-08-16 19:54 UTC, nhatduy227 commented on src/components/EditLocation/EditLocation.js
> +    if (isHomeDelivery && formData.address2 === '') {
I have remove this check on the form error

2021-08-16 19:58 UTC, nhatduy227 commented on src/components/EditLocation/EditLocation.js
> -          <div className="is_community_fridge">
I removed this because I think user don't need to check for the community fridge. The only difference of community fridge and normal recipient is community fridge. does not require a phone number. Therefore, I only check for phone number if it is input

2021-08-16 19:59 UTC, nhatduy227 commented on src/components/EditLocation/EditLocation.js
> +  const isHomeDelivery = organization
Done in newest push

2021-08-17 14:40 UTC, lukeshinnn requested changes
when address line 1 and 2 are the same (same address and apt #), the old location name is deleted and replaced with a new one. maybe in this circumstance, there should be a warning message that a duplicate address exists.
otherwise, LGTM!

2021-08-17 14:42 UTC, ryanmchenry2 commented
Luke that's a great callout - just to clarify, this occurs when you edit an existing location, and instead of modifying the original, it adds a brand new address?

> when address line 1 and 2 are the same (same address and apt #), the old location name is deleted and replaced with a new one. maybe in this circumstance, there should be a warning message that a duplicate address exists.
> 
> otherwise, LGTM!

2021-08-17 14:49 UTC, lukeshinnn commented
Ryan, so what i did was i went into an existing home delivery location (in this case, test home deliveries) and added two new locations with the exact same address line 1 and 2, called test 2 and test 4, respectively. when i added both, only the more recent location (test 4) was displayed and it replaced test 2 entirely

2021-08-17 14:57 UTC, ryanmchenry2 commented
> Ryan, so what i did was i went into an existing home delivery location (in this case, test home deliveries) and added two new locations with the exact same address line 1 and 2, called test 2 and test 4, respectively. when i added both, only the more recent location (test 4) was displayed and it replaced test 2 entirely

Just tested and confirmed this bug, looking at the code now to see why its happening and how to fix...

2021-08-17 14:59 UTC, ryanmchenry2 commented on src/components/EditLocation/EditLocation.js
>      const exists = await getCollection('Organizations')
@lukeshinnn @nhatduy227 I think this line is the problem here. We're checking to see if there's already an existing location with this uniq_id, but we're looking in the `Organizations` collection instead of `Locations`!

2021-08-17 15:00 UTC, ryanmchenry2 commented on src/components/EditLocation/EditLocation.js
>      const exists = await getCollection('Organizations')
I think we just need to fix that. ```const exists = await getCollection('Locations')....```

2021-08-17 15:00 UTC, nhatduy227 commented on src/components/EditLocation/EditLocation.js
>      const exists = await getCollection('Organizations')
oh ok let me try to change it

2021-08-17 15:02 UTC, nhatduy227 commented on src/components/EditLocation/EditLocation.js
>      const exists = await getCollection('Organizations')
Now it is able to send alert

2021-08-17 15:03 UTC, ryanmchenry2 commented on src/components/EditLocation/EditLocation.js
>      const exists = await getCollection('Organizations')
The two test cases that we need to for sure handle:
1. If I create a new location with an identical address to another location, it should create an error and not submit
2. If I edit an existing location that's ID was created before we used `address2` in the ID, it should still edit the existing location without creating a new/duplicate location

2021-08-17 15:06 UTC, nhatduy227 commented on src/components/EditLocation/EditLocation.js
>      const exists = await getCollection('Organizations')
I tried the 2 tests and I think it all pass, can someone confirm this?

2021-08-17 15:12 UTC, lukeshinnn reviewed
bug still seems to be happening on my end

2021-08-17 15:30 UTC, lukeshinnn approved these changes

2021-08-17 15:30 UTC, ryanmchenry2 approved these changes

2021-08-17 15:32 UTC, merged