Edit Location validation
sharingexcess/rescue pull request #96
Opened 2021-01-14 13:27 UTC by Chi-Bottle-Nguyen

- Adding validation to Edit Location form using validator library. The codes are based on Nom's work on Edit Organization for the sake of consistency and also his codes are good.
- A dropdown for states is also added
![image](https://user-images.githubusercontent.com/60493495/104596487-0b290500-5642-11eb-8ab0-724cdf1e488a.png)
![image](https://user-images.githubusercontent.com/60493495/104596592-2bf15a80-5642-11eb-9c37-1a745cb3ec83.png)

2021-01-14 15:04 UTC, nhatduy227 commented on src/components/EditLocation/EditLocation.js
> +    if (formData.name === '') {
this line should be formData.name === ' '. because if you put 1 letter to the input name it will still trigger the error to show

2021-01-14 15:05 UTC, nhatduy227 commented on src/components/EditLocation/EditLocation.js
> +    if (!formData.state.length || !validator.isAlpha(formData.state)) {
I don't think it is needed because the input of the States is a drop down so technically you can't enter numbers into it. Correct me if I am wrong

2021-01-14 15:06 UTC, nhatduy227 requested changes
There are some minor logic issues that need to be change. State drop down having  visibility issue in Dark mode

2021-01-14 15:15 UTC, Chi-Bottle-Nguyen commented on src/components/EditLocation/EditLocation.js
> +    if (!formData.state.length || !validator.isAlpha(formData.state)) {
you're right! will remove it

2021-01-15 09:04 UTC, Chi-Bottle-Nguyen commented on src/components/EditLocation/EditLocation.js
> +    if (formData.name === '') {
I'm not sure what you mean yet, but I just fixed the formData.name in a different way. Can you take a look?

2021-01-20 18:57 UTC, ryanmchenry2 approved these changes
Just added one small commit to adjust use of setErrors() and update required fields. As a general thought, I think less is more when it comes to form requirements. We never want to block someone from entering data because they're missing one piece if it's not completely essential.

Awesome PR, love the creation of a new smaller component, great best practice 👍  Excited to see this merged!

2021-01-20 18:57 UTC, ryanmchenry2 commented on src/components/EditLocation/EditLocation.js
> +      errors.push('Missing Location Name')
We want to avoid using errors.push(), because that means we're directly updating state rather than using a setState function, in this case setErrors(). While it seems like more code, a better solution might be setErrors([...errors, 'Missing Location Name'])

2021-01-20 18:57 UTC, ryanmchenry2 commented on src/components/EditLocation/EditLocation.js
> +      errors.push('Missing Location Name')
If we don't call setErrors, the component will not rerender by default, as the component won't know that it's state has changed.

2021-01-20 22:13 UTC, merged